// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIUIEKDRvGmJT9NaE2foyWnkeBA_ewjVk',
    appId: '1:570712488667:web:bbbdca7151d83045982afe',
    messagingSenderId: '570712488667',
    projectId: 'flux-ba73b',
    authDomain: 'flux-ba73b.firebaseapp.com',
    storageBucket: 'flux-ba73b.appspot.com',
    measurementId: 'G-F5Y11Q9TV2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqJIM2065WQxWsNbDnSdBCItTZ2uMgP18',
    appId: '1:570712488667:android:aee464a4a13566ae982afe',
    messagingSenderId: '570712488667',
    projectId: 'flux-ba73b',
    storageBucket: 'flux-ba73b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6fWE2AfDndvYkL6a-zFBN3nqvH9Nmpt0',
    appId: '1:570712488667:ios:c2e4f227265532a2982afe',
    messagingSenderId: '570712488667',
    projectId: 'flux-ba73b',
    storageBucket: 'flux-ba73b.appspot.com',
    iosBundleId: 'com.example.flux',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6fWE2AfDndvYkL6a-zFBN3nqvH9Nmpt0',
    appId: '1:570712488667:ios:c2e4f227265532a2982afe',
    messagingSenderId: '570712488667',
    projectId: 'flux-ba73b',
    storageBucket: 'flux-ba73b.appspot.com',
    iosBundleId: 'com.example.flux',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIUIEKDRvGmJT9NaE2foyWnkeBA_ewjVk',
    appId: '1:570712488667:web:84d8c4dc3ba868e0982afe',
    messagingSenderId: '570712488667',
    projectId: 'flux-ba73b',
    authDomain: 'flux-ba73b.firebaseapp.com',
    storageBucket: 'flux-ba73b.appspot.com',
    measurementId: 'G-HQZVTXTW6K',
  );
}
